
-- Question 15
-- Create a table COPYOFDEPT as copy of DEPT

CREATE TABLE DEPT (
    DNo NUMBER PRIMARY KEY,
    DName VARCHAR(50),
    ManagerSSN NUMBER,
    MgrStartDate DATE
);

INSERT INTO DEPT VALUES
(1, 'Finance', 1001, TO_DATE('01-JAN-2020','DD-MON-YYYY'));

CREATE TABLE COPYOFDEPT AS
SELECT * FROM DEPT;

SELECT * FROM COPYOFDEPT;
